version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-widget-render"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16h9tbla90mlp"
s3_prefix = "serverless-widget-render"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

